language: ruby
rvm:
- 2.0.0
- 2.1.0
- 2.1.4
- 2.1.5
- 2.2.0
- ruby-head
before_install:
- gem update --system
- gem --version
gemfile:
- Gemfile
notifications:
  slack:
    rooms:
      - day-one:ahrDZtNFpXqQiAzoM1fOmtbY#hackathons-dev
      - hackathonhackers:OPko6kxn8w4FZog32c8LWS4V#dev
sudo: true
script:
- rake db:create rake db:migrate
- rake
cache: bundler
addons:
  code_climate:
    repo_token: de88cc0f232b32ac8eb152d8d07c2e2f4dcebb07d1c8c3f12729299122af8ac6
services:
- mongodb
- postgresql