language: ruby
rvm:
- 2.0.0
- 2.1.0
- 2.1.4
- 2.1.5
- 2.2.0
- ruby-head
before_install:
- gem update --system
- gem --version
bundle_args: "--without unix"
gemfile:
- Gemfile
notifications:
  slack:
    secure: bp+CvRQjBH2B1QTWmlhopi6jDoZ8rCNQWLZTeTnZhjUTPm3GLY3Ymtrea8RusZukNsmNU7AsqY5Y8H/Zt70Mxx91j/m210k2QsEgYpmAgIJfdwaxhSvWpp92+s7+KR92+L2jRokebJmi7pShNEiYv5PHB/rqtNCBduqCA+rfTCI=
cache: bundler
addons:
  code_climate:
    repo_token: de88cc0f232b32ac8eb152d8d07c2e2f4dcebb07d1c8c3f12729299122af8ac6
services:
  - mongodb