language: ruby
rvm:
- 2.0.0
- 2.1.0
- 2.1.4
- 2.1.5
- 2.2.0
- ruby-head
before_install:
- gem update --system
- gem --version
bundle_args: "--without unix"
gemfile:
- Gemfile
notifications:
  slack:
    secure: FJ9dVL2r2m7TiTxBBkJdRmgXwz0b9d+cLh84soLoKBdzIlnL+tOgTDggkOeWtk1Ic9fg0nqoRq9Ns+uXTn5kS86V2f6p3QGCzLUldcQHV/oOxEgvPFYmKIPgSIsO9RsngmY+gbc3aq9i2SHctYtberUhb4FLiGCb4YP8P/GuDnc=
sudo: true
cache: bundler
addons:
  code_climate:
    repo_token: de88cc0f232b32ac8eb152d8d07c2e2f4dcebb07d1c8c3f12729299122af8ac6
services:
- mongodb
